<a href="https://colab.research.google.com/github/Suman18-bit/NLP_CHALANGES/blob/main/Sentiment%20Analysis%20with%20VADER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# %%capture
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00331/sentiment%20labelled%20sentences.zip

--2026-06-22 05:40:46--  https://archive.ics.uci.edu/ml/machine-learning-databases/00331/sentiment%20labelled%20sentences.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘sentiment labelled sentences.zip’

sentiment labelled      [ <=>                ]  82.21K  --.-KB/s    in 0.1s

2026-06-22 05:40:47 (840 KB/s) - ‘sentiment labelled sentences.zip’ saved [84188]

In [ ]:
!unzip sentiment\ labelled\ sentences.zip

Archive:  sentiment labelled sentences.zip
   creating: sentiment labelled sentences/
  inflating: sentiment labelled sentences/.DS_Store
   creating: __MACOSX/
   creating: __MACOSX/sentiment labelled sentences/
  inflating: __MACOSX/sentiment labelled sentences/._.DS_Store
  inflating: sentiment labelled sentences/amazon_cells_labelled.txt
  inflating: sentiment labelled sentences/imdb_labelled.txt
  inflating: __MACOSX/sentiment labelled sentences/._imdb_labelled.txt
  inflating: sentiment labelled sentences/readme.txt
  inflating: __MACOSX/sentiment labelled sentences/._readme.txt
  inflating: sentiment labelled sentences/yelp_labelled.txt
  inflating: __MACOSX/._sentiment labelled sentences

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/sentiment labelled sentences/amazon_cells_labelled.txt',sep='\t',names = ['review','labelled_sentiment'])
df2 = pd.read_csv('/content/sentiment labelled sentences/imdb_labelled.txt',sep='\t',names = ['review','labelled_sentiment'])
df3 = pd.read_csv('/content/sentiment labelled sentences/yelp_labelled.txt',sep='\t',names = ['review','labelled_sentiment'])

In [ ]:
print(df1.head(),"  \n",df2.head(),"  \n",df3.head())

                                              review  labelled_sentiment
0  So there is no way for me to plug it in here i...                   0
1                        Good case, Excellent value.                   1
2                             Great for the jawbone.                   1
3  Tied to charger for conversations lasting more...                   0
4                                  The mic is great.                   1
                                               review  labelled_sentiment
0  A very, very, very slow-moving, aimless movie ...                   0
1  Not sure who was more lost - the flat characte...                   0
2  Attempting artiness with black & white and cle...                   0
3       Very little music or anything to speak of.                     0
4  The best scene in the movie was when Gerardo i...                   1
                                               review  labelled_sentiment
0                           Wow... Loved this place.                   1
1                                 Crust is not good.                   0
2          Not tasty and the texture was just nasty.                   0
3  Stopped by during the late May bank holiday of...                   1
4  The selection on the menu was great and so wer...                   1

In [ ]:
df = pd.concat([df1,df2,df3],axis=0,ignore_index=True)

In [ ]:
df.head()

                                              review  labelled_sentiment
0  So there is no way for me to plug it in here i...                   0
1                        Good case, Excellent value.                   1
2                             Great for the jawbone.                   1
3  Tied to charger for conversations lasting more...                   0
4                                  The mic is great.                   1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2748 entries, 0 to 2747
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   review              2748 non-null   object
 1   labelled_sentiment  2748 non-null   int64
dtypes: int64(1), object(1)
memory usage: 43.1+ KB

In [ ]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.5.20)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 3.1 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
import vaderSentiment

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [ ]:
Analyzer = SentimentIntensityAnalyzer()

In [ ]:
df['vaderSentiment_score'] = df['review'].apply(lambda x:Analyzer.polarity_scores(x)['compound'])

In [ ]:
df.head()

,review,labelled_sentiment,vaderSentiment_score
0,So there is no way for me to plug it in here i...,0,-0.3535
1,"Good case, Excellent value.",1,0.8402
2,Great for the jawbone.,1,0.6249
3,Tied to charger for conversations lasting more...,0,-0.6145
4,The mic is great.,1,0.6249

In [ ]:
df['vaderSentiment'] = df['vaderSentiment_score'].map(lambda x:int(1) if x>0.05 else int(0) if x<=-0.05 else int(2))

In [ ]:
df.head()

,review,labelled_sentiment,vaderSentiment_score,vaderSentiment
0,So there is no way for me to plug it in here i...,0,-0.3535,0
1,"Good case, Excellent value.",1,0.8402,1
2,Great for the jawbone.,1,0.6249,1
3,Tied to charger for conversations lasting more...,0,-0.6145,0
4,The mic is great.,1,0.6249,1

In [ ]:
df['vaderSentiment'].unique()

array([0, 1, 2])

In [ ]:
df['vaderSentiment'] = df['vaderSentiment'].map({0:'negative',1:'positive',2:'neutral'})

In [ ]:
df

,review,labelled_sentiment,vaderSentiment_score,vaderSentiment
0,So there is no way for me to plug it in here i...,0,-0.3535,negative
1,"Good case, Excellent value.",1,0.8402,positive
2,Great for the jawbone.,1,0.6249,positive
3,Tied to charger for conversations lasting more...,0,-0.6145,negative
4,The mic is great.,1,0.6249,positive
...,...,...,...,...
2743,I think food should have flavor and texture an...,0,0.0000,neutral
2744,Appetite instantly gone.,0,0.0000,neutral
2745,Overall I was not impressed and would not go b...,0,-0.3724,negative
2746,"The whole experience was underwhelming, and I ...",0,0.0000,neutral
2747,"Then, as if I hadn't wasted enough of my life ...",0,0.3875,positive